### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by ChenYuWuAi** [TartaricAcid/tartaricacid.github.io#1]
Hello Mr.943.Did you remember me?Your blog is so good~~~
哇，你发现了一个神秘的地方，奖励你一朵小红花。

**Comment by ChenYuWuAi** [comment]
其实您可以试试：deepin/elementary os。他们都是基于debian的，后者基于ubuntu。其实ubuntu就是基于debian的，还有，等到18.04 LTS出来之后就没有Unity了，会是Gnome，所以请三思。

**Comment by TartaricAcid** [comment]
……看起来我的博客的确需要一个评论系统
多谢指导

**Comment by TartaricAcid** [comment]
评论系统已经弄好了，现在进入分页文章下方即可评论
https://github.com/TartaricAcid/tartaricacid.github.io/commit/46df29d9ca1d7b15764be30ff2ddbf0495dc0586
